import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Footer from "@/components/Footer";

import dynamic from "next/dynamic";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const NavBarNoSSR = dynamic(() => import('../components/NavBar'), { ssr: false })
const NavBarDesktopNoSSR = dynamic(() => import('../components/NavBarDesktop'), { ssr: false })

export default function RootLayout({ children, }: { children: React.ReactNode; }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBarNoSSR />
        <main className="flex flex-col lg:grid lg:grid-cols-[260px_minmax(0,1fr)]  ">
          <section className=" lg:col-span-1">
            <NavBarDesktopNoSSR />
          </section>
          <section className="lg:col-start-2 min-h-screen w-full bg-gray-400 flex flex-col">
            <section className="min-h-screen">{children}</section>
            <Footer />
          </section>
        </main>
      </body>
    </html>
  );
}
